name: final_project
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - scipy
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - plotly
  - pip
  - gap-statistic
  - pillow
  - opencv-python
